// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhpfvjgkfffkpisvotpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVocGZ2amdrZmZma3Bpc3ZvdHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzA5NTcsImV4cCI6MjA2OTMwNjk1N30.JzntXeCwsnAc4Vwys8O3cc_ok6M4wtwezwIvGwLzKqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});